Rails.application.routes.draw do
 root to: 'hr#index' 
 get '/department', to: 'hr#department'
 get '/emp_qualification', to: 'hr#emp_qualification'
 get '/attendence', to: 'hr#attendence'
 #get '/add_employee', to: 'hr#add_employee'
 get '/add_department', to: 'hr#add_department'
 get '/add_qualification', to: 'hr#add_qualification'
 get '/add_attendence', to: 'attendence#new'
 get '/employee/new', to: 'employee#new'
 get '/qualification/new', to: 'qualification#new'
# post '/create_employee', to: 'hr#create_employee'
 get '/emp_detail', to: 'hr#emp_detail'
 get '/add_employee', to: 'employee#new'
 # post '/create_employee', to: 'hr#create_employee'
 post '/create_department', to: 'hr#create_department'
 post '/create_qualification', to: 'hr#create_qualification'
 post '/create_attendence', to: 'hr#create_attendence'
 post '/create/emp', to: 'employee#create'
 post '/create/emp_q', to: 'qualification#create'
 post 'attendence/create', to: 'attendence#create'
 # post '/create', to: 'employee#create'
 delete '/delete_employee', to: 'hr#delete_employee'
 delete '/delete_qualification', to: 'hr#delete_qualification'
 delete '/delete_department', to: 'hr#delete_department'
 delete '/delete_attendence', to: 'hr#delete_attendence'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
