# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ddae1755422cdccbb90bad12f00e487f9dd86989772550986b883f6b75ce7374870004c9d3099cf0ea762ffaaf364870384c90ffd052ed9fb6760d9f774d92

test:
  secret_key_base: b1c9a0c85d3d04b3f9076e221b319d7105562928823cad2fbd1d6230780401b6ef468af4298cea605cdf89329c9f7dc20aa63088d8067838054c6dbf43acfd1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
